spring.application.name=programadepontos

# Configuração do banco em memória H2
spring.datasource.url=jdbc:h2:mem:programadepontosdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilita o console visual do H2 no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Atualiza as tabelas automaticamente de acordo com as @Entity
spring.jpa.hibernate.ddl-auto=update